#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'
include FileUtils

# from http://errtheblog.com/posts/89-huba-huba

# This is idempotent, meaning you can run it over and over again without fear of
# breaking anything. Use it as an installer or to upgrade after merging from an
# upstream fork.

HOME = File.expand_path('~')
DOTFILES_ROOT = Pathname.new File.expand_path('../../', __FILE__)

chdir DOTFILES_ROOT do
  Dir['*'].each do |file|
    next if file =~ /script/ || file =~ /README/
    target = File.join(HOME, ".#{file}")
    `ln -ns #{File.expand_path file} #{target}`
  end
end

# Brewfile isn't a dotfile
system("ln -ns #{File.join(HOME, '.Brewfile')} Brewfile")

# always overwrite a gitconfig that may have been generated elsewhere
system("ln -nsF #{File.join(DOTFILES_ROOT, 'gitconfig')} .gitconfig")
