#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'
include FileUtils

# from http://errtheblog.com/posts/89-huba-huba

# This is idempotent, meaning you can run it over and over again without fear of
# breaking anything. Use it as an installer or to upgrade after merging from an
# upstream fork.

HOME = File.expand_path('~')
DOTFILES_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def setup_for_custom_ink_codespaces
  `cat /workspaces/.codespaces/.persistedshare/dotfiles/bashrc >> $HOME/.bashrc`
  setup_for_normal_env
end

def setup_for_normal_env
  Dir['*'].each do |file|
    next if file =~ /script/ || file =~ /README/
    target = File.join(HOME, ".#{file}")
    `ln -ns #{File.expand_path file} #{target}`
  end

  # ~/Brewfile isn't a dotfile
  target = File.join(HOME, 'Brewfile')
  system("ln -nsf #{File.join(DOTFILES_ROOT, 'Brewfile')} #{target}")

  # always overwrite a ~/.gitconfig that may have been generated elsewhere
  target = File.join(HOME, '.gitconfig')
  system("ln -nsf #{File.join(DOTFILES_ROOT, 'gitconfig')} #{target}")
end

if ENV['CODESPACES'] == "true"
  setup_for_custom_ink_codespaces
else
  setup_for_normal_env
end
